import os
from typing import Any

from supabase import create_client, Client
from dotenv import load_dotenv

load_dotenv()

url: str = os.environ.get("SUPABASE_URL", "")
key: str = os.environ.get("SUPABASE_KEY", "")

supabase: Client = None

if url and key and url != "your_supabase_url":
    supabase = create_client(url, key)


def is_supabase_configured() -> bool:
    return supabase is not None


def _invoices_table_missing(error: Exception) -> bool:
    msg = str(error).lower()
    return "invoices" in msg and (
        "does not exist" in msg
        or "relation" in msg
        or "42p01" in msg
        or "pgrst205" in msg
        or "schema cache" in msg
        or "could not find the table" in msg
    )


def _execute_schema_sql(sql: str) -> bool:
    if not supabase:
        return False

    for fn_name in ("exec_sql", "run_sql", "execute_sql"):
        try:
            supabase.rpc(fn_name, {"sql": sql}).execute()
            return True
        except Exception:
            continue

    return False


def ensure_invoices_table() -> bool:
    if not supabase:
        raise RuntimeError("Supabase client is not configured. Set SUPABASE_URL and SUPABASE_KEY.")

    try:
        supabase.table("invoices").select("id").limit(1).execute()
        return True
    except Exception as e:
        if not _invoices_table_missing(e):
            raise

    create_sql = """
    create table if not exists public.invoices (
        id bigint generated by default as identity primary key,
        amount numeric not null,
        owner text not null,
        status text not null
    );
    """
    created = _execute_schema_sql(create_sql)
    if not created:
        raise RuntimeError(
            "The 'invoices' table is missing and could not be auto-created via RPC. "
            "Create it in Supabase SQL editor with columns: id, amount, owner, status."
        )

    return True

def get_app_state():
    if not supabase:
        return {"app_id": 0, "supplier_addr": "", "investor_addr": ""}
    
    try:
        response = supabase.table("app_state").select("*").order("updated_at", desc=True).limit(1).execute()
        if response.data:
            return response.data[0]
    except Exception as e:
        print(f"Error fetching app state: {e}")
    
    return {"app_id": 0, "supplier_addr": "", "investor_addr": ""}

def update_app_state(app_id: int = None, supplier_addr: str = None, investor_addr: str = None):
    if not supabase:
        return
    
    data = {}
    if app_id is not None:
        data["app_id"] = app_id
    if supplier_addr is not None:
        data["supplier_addr"] = supplier_addr
    if investor_addr is not None:
        data["investor_addr"] = investor_addr
    
    if not data:
        return

    data["updated_at"] = "now()"

    try:
        # We always update the first row (or insert if none exists)
        # For simplicity in this PoC, we'll just insert a new row or update the latest
        current = get_app_state()
        if current.get("id"):
            supabase.table("app_state").update(data).eq("id", current["id"]).execute()
        else:
            supabase.table("app_state").insert(data).execute()
    except Exception as e:
        print(f"Error updating app state: {e}")


def test_supabase_connection() -> dict[str, Any]:
    if not supabase:
        raise RuntimeError("Supabase client is not configured. Set SUPABASE_URL and SUPABASE_KEY.")

    ensure_invoices_table()
    response = supabase.table("invoices").select("*").limit(5).execute()
    return {
        "ok": True,
        "rows": response.data or []
    }


def create_invoice_record(amount: float, owner: str, status: str = "pending") -> dict[str, Any]:
    ensure_invoices_table()
    payload = {
        "amount": amount,
        "owner": owner,
        "status": status,
    }
    response = supabase.table("invoices").insert(payload).execute()
    if not response.data:
        raise RuntimeError("Invoice insert returned no data")
    return response.data[0]


def fetch_all_invoices() -> list[dict[str, Any]]:
    ensure_invoices_table()
    response = supabase.table("invoices").select("*").order("id", desc=False).execute()
    return response.data or []


def update_invoice_status_record(invoice_id: Any, status: str) -> dict[str, Any]:
    ensure_invoices_table()
    response = supabase.table("invoices").update({"status": status}).eq("id", invoice_id).execute()
    if not response.data:
        raise RuntimeError(f"Invoice {invoice_id} not found")
    return response.data[0]


def fetch_invoice_by_id(invoice_id: Any) -> dict[str, Any]:
    ensure_invoices_table()
    response = supabase.table("invoices").select("*").eq("id", invoice_id).limit(1).execute()
    if not response.data:
        raise RuntimeError(f"Invoice {invoice_id} not found")
    return response.data[0]


def insert_sample_invoice() -> dict[str, Any]:
    return create_invoice_record(amount=1234.56, owner="sample-owner", status="pending")
